name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install poetry
        run: pipx install poetry
      - name: setup latest python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: poetry
      - name: build new version ${{ env.GITHUB_REF_NAME }}
        run: |
          poetry version ${GITHUB_REF_NAME#v}
          poetry build
      - uses: pypa/gh-action-pypi-publish@release/v1
      - name: upload new release ${{ env.GITHUB_REF_NAME }}
        run: gh release upload $GITHUB_REF_NAME dist/*
        env:
          GH_TOKEN: ${{ github.token }}
